# Generated by Django 4.0.5 on 2022-06-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='unsubscriber_key',
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='unsubscribe_key',
            field=models.UUIDField(auto_created=True, blank=True, unique=True),
            preserve_default=False,
        ),
    ]
