# Generated by Django 3.2.4 on 2022-05-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220527_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='metadescription',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='metadescription',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
