# Generated by Django 3.2.4 on 2022-05-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20220527_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='metadescription',
        ),
        migrations.RemoveField(
            model_name='post',
            name='metadescription',
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
