# Generated by Django 4.0.5 on 2022-06-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220527_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('meta_description', models.CharField(max_length=155)),
                ('slug', models.SlugField()),
                ('posts', models.ManyToManyField(related_name='tags', to='blog.post')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ('title',),
            },
        ),
    ]
